version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-weakdefault}
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_STD_USER: ${POSTGRES_STD_USER:-patientport}
      POSTGRES_STD_USER_PWD: ${POSTGRES_STD_USER_PWD:-defaultpwd}
      POSTGRES_STD_DB: ${POSTGRES_STD_DB:-patientport}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      - ./initdb:/docker-entrypoint-initdb.d/:ro
    ports:
      - "127.0.0.1:5432:5432"
    labels:
      com.symfony.server.service-prefix: POSTGRES_STD_
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
