#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER $POSTGRES_STD_USER PASSWORD '$POSTGRES_STD_USER_PWD';
	CREATE DATABASE $POSTGRES_STD_DB OWNER $POSTGRES_STD_USER;
EOSQL
